# WebSafeFonts = true
# logoMark = 'https://example.com/logoMark.svg'
# logoMarkDark = 'https://example.com/logoMarkDark.svg'
logoType = true
extMeta = true
coffeeStat = true

[typeface] # webSafeFonts must be disabled
    roman = 'crimson' # available option: 'Crimson' 'Cormorant', default: 'EB Garamond'
    sans = 'inter' # available option: 'Inter', 'Monserrat', default: 'Rosario'

[author]
    name = 'Author Name'
    email = 'email@example.com'
    coauthor = [ # other method to add co-authors's bio
        {name = "A.N. Other", bio = "Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum."}
    ]

[feed]
    flowlines = true
    flowlinesLimit = 21

[search]
    enable = true
    pagefind  = true